### ISSUE TITLE
requirements.txt

### ISSUE THREAD

**Issue by Fadouagh** [mchong6/JoJoGAN#12]
Could you please add requirements.txt file.
I would like to run the code locally in a docker container.

**Comment by mchong6** [comment]
You can see what is required by looking at what is being installed in the colab.

**Comment by Fadouagh** [comment]
That is right. Thanks.

!```
git clone https://github.com/mchong6/JoJoGAN.git
%cd JoJoGAN
!pip install tqdm gdown scikit-learn==0.22 scipy lpips dlib opencv-python wandb
!wget https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-linux.zip
!sudo unzip ninja-linux.zip -d /usr/local/bin/
!sudo update-alternatives --install /usr/bin/ninja ninja /usr/local/bin/ninja 1 --force
```
