### ISSUE TITLE
resume training

### ISSUE THREAD

**Issue by osushilover** [mchong6/JoJoGAN#15]
I'm interested in this grateful project.
And I've tried to train my own model on Colab.
Please let me know how to resume training.

**Comment by mchong6** [comment]
You can save a model by running 
`torch.save({"g": generator.state_dict()}, f"checkpoint.pt") `

and then when you want to resume the training load it 
`ckpt = torch.load('model.pt', map_location=lambda storage, loc: storage)
generator.load_state_dict(ckpt["g"], strict=False)
`

**Comment by osushilover** [comment]
Yes, I could!
Thank you for your reply, sir.
