### ISSUE TITLE
How many paired images of dataset C in the paper

### ISSUE THREAD

**Issue by zhongtao93** [mchong6/JoJoGAN#16]
Hi, thank you for sharing source code. 
I can't find how many paired image of dataset C. From your experiment, at least how many paired (wi, y) can have a good result?

**Comment by mchong6** [comment]
Each training iteration creates a new (wi, y). Normally it takes 200~500 of batch size 1 iteration, thus it creates 200~500 paired data. I never tested how many you absolutely need, i.e. create only 10 pairs and train 500 iterations on the 10 pairs.

**Comment by zhongtao93** [comment]
Thanks, so it selects new(wi, y) automatically instead of manually. I'll study the code carefully.
