### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by AK391** [mchong6/JoJoGAN#2]
when device is set to cpu in colab and hardware accelerator is none

No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-1-4973789e8df1> in <module>()
     24 from tqdm import tqdm
     25 import lpips
---> 26 from model import *
     27 from e4e_projection import projection as e4e_projection
     28 from restyle_projection import projection as restyle_projection

7 frames
/usr/local/lib/python3.7/dist-packages/torch/utils/cpp_extension.py in _get_cuda_arch_flags(cflags)
   1604                 arch_list.append(arch)
   1605         arch_list = sorted(arch_list)
-> 1606         arch_list[-1] += '+PTX'
   1607     else:
   1608         # Deal with lists that are ' ' separated (only deal with ';' after)

IndexError: list index out of range

**Comment by mchong6** [comment]
Should be fixed now!

**Comment by AK391** [comment]
@mchong6 thanks!
