### ISSUE TITLE
Perceptual loss: LPIPS vs. StyleGAN Discriminator

### ISSUE THREAD

**Issue by matanby** [mchong6/JoJoGAN#22]
Hi!

Thanks for sharing this awesome work :-) 

I'm wondering on the difference in perceptual image quality when using the LPIPS model (as stated in the paper) vs. the StyleGAN discriminator (as used in the updated collab notebook) for the perceptual loss.
In your experience, what kind of  difference does using the StyleGAN discriminator have on the image quality, when compared to using LPIPS?

**Comment by mchong6** [comment]
Hi, the paper should be updated on arxiv with some comparison. But generally lpips captures less details and has some downsampling artifacts.

**Comment by matanby** [comment]
I've just noticed the updated paper, and read through the relevant section. Thanks for the answer!
