### ISSUE TITLE
A question about how to preserve colors

### ISSUE THREAD

**Issue by PanggNOTlovebean** [mchong6/JoJoGAN#24]
The following methods are used in the source code to preserve the color
`if preserve_color:`
`    id_swap = [9,11,15,16,17]`
`else:`
`    id_swap = list(range(7, generator.n_latent))`

I wanna know how to get the exact ID of these layers. 
Are there some papers that introduce such things? Or through a lot of attempts to know which layers control the color?

**Comment by mchong6** [comment]
I tried manually to see which layers control colors the most.
