### ISSUE TITLE
alternative to dlib for face alignment

### ISSUE THREAD

**Issue by AK391** [mchong6/JoJoGAN#5]
dlib is very slow to build, possible to use a alternative like from here https://github.com/happy-jihye/FFHQ-Alignment, for example https://github.com/happy-jihye/FFHQ-Alignment/blob/master/FFHQ-Alignmnet/ffhq-align.py

more example usage here: https://github.com/happy-jihye/FFHQ-Alignment/blob/master/FFHQ-Alignmnet/FFHQ-Alignment.ipynb

**Comment by mchong6** [comment]
Thanks for the suggestion. I will have to experiment a little to see if it is as robust as dlib which works pretty consistently across face and anime images :)

**Comment by AK391** [comment]
@mchong6 great, also see https://github.com/xinntao/facexlib, it is used in gfpgan https://github.com/TencentARC/GFPGAN

**Comment by AK391** [comment]
closing this for now
