### ISSUE TITLE
save finetuned model

### ISSUE THREAD

**Issue by AK391** [mchong6/JoJoGAN#6]
are the finetuned models saved currently in the colab?

**Comment by mchong6** [comment]
The fine-tuned models are not currently saved as they will disappear after the session. There probably is a way to save it directly to your GDrive. Is that something you want?

**Comment by AK391** [comment]
@mchong6 oh I actually meant in the colab notebook I could not find the location, let me check again

**Comment by mchong6** [comment]
I did not save it in the colab notebook. To save it you can run 

`    torch.save(
        {
            "g": generator.state_dict(),
        },
        f"checkpoint.pt",
`

**Comment by AK391** [comment]
@mchong6 ok thanks
